version: 1
formatters:
  simple:
    format: '%(asctime)-15s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  flair:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: WARNING
  handlers: [console]